// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"bphn/artikel-hukum/internal/server"
	"bphn/artikel-hukum/pkg/app"
	"bphn/artikel-hukum/pkg/log"
	server2 "bphn/artikel-hukum/pkg/server"
	"github.com/google/wire"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func InitializeApp(viper2 *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	httpServer := server.NewHttpServer(viper2, logger)
	appApp := newServer(httpServer)
	return appApp, func() {
	}, nil
}

// wire.go:

var serverSet = wire.NewSet(server.NewHttpServer)

func newServer(httpServer *server2.HttpServer) *app.App {
	return app.NewApp(app.WithServer(httpServer), app.WithName("artikel-hukum-api"))
}
