env: local
http:
  host: 0.0.0.0
  port: 8080
security:
  jwt:
    key: F93NNkrDA2Ni1MOdmCZW7todmWHJ+8SQJdsEeFvkK1g=
data:
  mysql:
    host: 127.0.0.1
    port: 3306
    username: root
    password: 12345678
    database: db_artikel_hukum
log:
  log_level: debug
  encoding: console           # json or console
  log_file_name: "./storage/logs/web.log"
  max_backups: 30
  max_age: 7
  max_size: 1024
  compress: true