// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"bphn/artikel-hukum/internal/repository"
	"bphn/artikel-hukum/internal/server/migration"
	"bphn/artikel-hukum/pkg/app"
	"bphn/artikel-hukum/pkg/log"
	"github.com/google/wire"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func InitializeMigration(viper2 *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	db := repository.NewDB(viper2, logger)
	migration := migration.NewMigration(db, logger)
	appApp := newApp(migration)
	return appApp, func() {
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewRepository)

func newApp(migration *migration.Migration) *app.App {
	return app.NewApp(app.WithName("database-migration"), app.WithServer(migration))
}
